# curses_adapter.py
from abc import ABC, abstractmethod
from typing import Tuple, List
from service.enums.ColorEnum import Color

class ICursesService:
    def init(self) -> None: ...
    
    def cleanup(self) -> None: ...
    
    def get_screen_size(self) -> Tuple[int, int]: ...
    
    def clear(self) -> None: ...
    
    def refresh(self) -> None: ...
    
    def add_str(self, y: int, x: int, text: str, 
                fg: Color = Color.WHITE, bg: Color = Color.BLACK, 
                attributes: List[str] = None) -> None: ...
    
    def add_str_centered(self, y: int, text: str,
                        fg: Color = Color.WHITE, bg: Color = Color.BLACK,
                        attributes: List[str] = None) -> None: ...
    
    def draw_box(self, y: int, x: int, height: int, width: int,
                fg: Color = Color.WHITE, bg: Color = Color.BLACK) -> None: ...
    
    def get_key(self) -> str: ...
    
    def set_cursor(self, y: int, x: int) -> None: ...
    
    def hide_cursor(self) -> None: ...
    
    def show_cursor(self) -> None: ...